name: Package

on:
  push:
    branches:
      - master
      - classic
    tags:
      - '*'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags') == true || contains(github.event.head_commit.message, 'skip ci') != true

    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Run luacheck
      uses: nebularg/actions-luacheck@v1

    - name: Package and release
      uses: BigWigsMods/packager@master
